### ISSUE TITLE
High CPU usage compared to master branch's version

### ISSUE THREAD

**Issue by Geremia** [bitcoinknots/bitcoin#1]
It would seem that Bitcoin Knots, because of its SPAM filtering, would not use as much of the CPU processing transactions as Core does, yet two threads of it use >100% CPU on my multicore machine. This only occurs while the memory pool is filling up to its max size (default: 300 MB). Once it gets close to 300 MB, the CPU % usage drops down to normal levels.

**Comment by luke-jr** [comment]
All transactions mined into the blockchain _must_ be processed by full nodes - that's unavoidable. But when not syncing blocks, CPU usage should be minimal.

Re "compared to master branch": Are you seeing higher CPU usage in Knots than with Core?

**Comment by Geremia** [comment]
@luke-jr Yes, higher CPU usage with Knots than Core, at least while the memory pool is filling up to its max size (default: 300 MB).

**Comment by Geremia** [comment]
@luke-jr This issue seems to have been fixed with 0.13.0.knots20160814.

**Comment by luke-jr** [comment]
Good to hear, thanks for testing. :)
