### ISSUE TITLE
CWalette::nRelockTime is not initialised

### ISSUE THREAD

**Issue by greenius** [bitcoinknots/bitcoin#12]
In src/wallet/walette..h a new instance variable nRelockTime has been added.

When starting bitcoind the value of nRelockTime is set to a random value of whatever happens to be in memory at that time.

#### If so, please list the steps to reproduce below:
1. Start bitcoind
2. run bitcoin-cli getinfo
3. Note that "unlocked_until": line has an non-zero value

### Expected behaviour
getinfo : unlocked_until should display 0 after bitcoind has been started.

### Actual behaviour
unlocked_until has a random value (which can be cleared with "bitcoin-cli walletlock")

### What version of Bitcoin Knots are you using?
Latest git:  origin/0.14.x-knots

Note that bitcoin-core 0.15 also has this nRelockTime instance but sets the value to 0 in CWalette::SetNull().

**Comment by luke-jr** [comment]
Please confirm this is fixed in Knots 0.15.0.

**Comment by greenius** [comment]
Yes. It is working in Knots 0.15.0. Thanks.
