### ISSUE TITLE
Release for Bitcoin Core 0.17.0.1

### ISSUE THREAD

**Issue by candrews** [bitcoinknots/bitcoin#16]
Bitcoin core released version 0.17.0.1: https://github.com/bitcoin/bitcoin/releases/tag/v0.17.0.1

Can you please create a corresponding release of knots?

**Comment by luke-jr** [comment]
It's a work-in-progress. Core v0.17 has quite a few regressions that are being addressed first.

**Comment by luke-jr** [comment]
https://github.com/bitcoinknots/bitcoin/blob/v0.17.1.knots20181229/doc/release-notes.md
