### ISSUE TITLE
Unit selection menu repeats after satoshis, instead of showing TBC options and ending

### ISSUE THREAD

**Issue by Geremia** [bitcoinknots/bitcoin#17]
Tonal units (TBC) are no longer an option for me after having upgraded from 0.17.0.knots → 0.17.1.knots. Instead, I get this strange infinitely repeating popup menu, but with no TBC options:

[![unit popup menu][1]][1]

  [1]: https://i.stack.imgur.com/kLO0m.png

**Comment by luke-jr** [comment]
I found the issue that can cause it to repeat, but are you sure TBC was an option on your system previously? The logic to detect Tonal availability hasn't changed...

**Comment by Geremia** [comment]
@luke-jr Yes, I had working tonal functionality previously. I still have the tonal fonts installed.

**Comment by luke-jr** [comment]
Does v0.18.0 work, or still has the problem? Are you able to debug it at all?

**Comment by Geremia** [comment]
@luke-jr TBC doesn't appear as an option in the units menu anymore.
I'm running v0.21.0.knots20210130.

**Comment by luke-jr** [comment]
Are you able to compile a patch? Can we interactively debug this on Twitter or IRC or something?

**Comment by Geremia** [comment]
@luke-jr Sent you a question on #eligius, and I get "Cannot send to nick/channel". hmm.
Does Knots have its own channel?
