### ISSUE TITLE
Duplicated TBC calculations & character encoding issue

### ISSUE THREAD

**Issue by btcusury** [bitcoinknots/bitcoin#20]
Since a few versions ago (now using v0.17.1.knots20181229 (64-bit) from website), this happens:

![knots-bug-confirm-tbc](https://user-images.githubusercontent.com/49042131/55187903-630b2900-519a-11e9-88e4-c640641fd8b8.png)

Aside from the character encoding issue, the number of repeated lines seems to multiply after every transaction (resets on reopen), similar to the other reported "unit selection menu" bug. A few versions ago IIRC the only issue was the Chinese characters.

On Win7 x64, i7, HDD.

**Comment by luke-jr** [comment]
Hmm, it looks like you have a font that puts Chinese characters at the Tonal codepoints.

I wonder if there's a good way to detect this issue.

**Comment by luke-jr** [comment]
Does this issue affect newer versions?

**Comment by btcusury** [comment]
Hi, the duplication issue seems fixed, but I still get Chinese characters.

BTW, are you aware of a single person anywhere that finds use in the tonal bitcoin system?
