### ISSUE TITLE
Segfault with 0.18.0.knots20190502-bionic0 from the PPA

### ISSUE THREAD

**Issue by freerko** [bitcoinknots/bitcoin#21]
Hi,
on a server with Ubuntu 18.04 I try to run 0.18.0.knots20190502-bionic0 from your PPA. When starting bitcoind I immediately get a segfault. The debug.log stops at:

> 2019-07-12T18:32:07Z Using wallet directory /var/lib/bitcoin/.bitcoin
2019-07-12T18:32:07Z init message: Verifying wallet(s)...
2019-07-12T18:32:07Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2019-07-12T18:32:07Z Using wallet /var/lib/bitcoin/.bitcoin
2019-07-12T18:32:07Z BerkeleyEnvironment::Open: LogDir=/var/lib/bitcoin/.bitcoin/database ErrorFile=/var/lib/bitcoin/.bitcoin/db.log
2019-07-12T18:32:07Z scheduler thread start
2019-07-12T18:32:08Z

Syslog logs:

> Jul 12 19:19:16 hostname systemd[1]: Started Bitcoin daemon.
Jul 12 19:19:16 hostname kernel: [  131.197945] bitcoin-schedul[1371]: segfault at 7ff40cd14fb0 ip 00007ff40a603fa0 sp 00007ff406af5118 error 4 in libpthread-2.27.so[7ff40a5fa000+1a000]
Jul 12 19:19:17 hostname systemd[1]: bitcoind.service: Main process exited, code=killed, status=11/SEGV
Jul 12 19:19:17 hostname systemd[1]: bitcoind.service: Failed with result 'signal'.
Jul 12 19:19:17 hostname systemd[1]: bitcoind.service: Service hold-off time over, scheduling restart.
Jul 12 19:19:17 hostname systemd[1]: bitcoind.service: Scheduled restart job, restart counter is at 5.
Jul 12 19:19:17 hostname systemd[1]: Stopped Bitcoin daemon.
Jul 12 19:19:17 hostname systemd[1]: bitcoind.service: Start request repeated too quickly.
Jul 12 19:19:17 hostname systemd[1]: bitcoind.service: Failed with result 'signal'.
Jul 12 19:19:17 hostname systemd[1]: Failed to start Bitcoin daemon.

I run bitcoinknots on that server since several years already and according to the logs this started on 2019-05-04 when I updated to bitcoinknots 0.18, but on that day I installed other package updates and finally configuring systemd as well.
I found https://github.com/bitcoin/bitcoin/issues/12047 which suggests segfaults might happen when using incompatible BDB versions. Just as the user reporting that issue I have two different versions installed:

> root@hostname:~# dpkg -l | grep libdb
ii  libdb4.8++                            4.8.30-bionic1                    amd64        Berkeley v4.8 Database Libraries for C++ [runtime]
ii  libdb5.3:amd64                        5.3.28-13.1ubuntu1.1              amd64        Berkeley v5.3 Database Libraries [runtime]

On other servers I run bitcoind from Matt Corallos PPA which ships the libdb4.8++ package 4.8.30-bionic3 compiled on 2018-03-05. Those servers have the ubuntu package libdb5.3:amd64 installed as well but there are no segfaults. In your PPA you ship libdb4.8++ as version 4.8.30-bionic1 compiled on 2017-11-12.

Any idea what could be wrong here?

More details of the segfault:

> root@hostname:~ # valgrind /usr/bin/bitcoind -daemon -conf=/etc/bitcoin/bitcoin.conf -pid=/run/bitcoind/bitcoind.pid
==9459== Memcheck, a memory error detector
==9459== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==9459== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==9459== Command: /usr/bin/bitcoind -daemon -conf=/etc/bitcoin/bitcoin.conf -pid=/run/bitcoind/bitcoind.pid
==9459==
==9459== Invalid read of size 16
==9459==    at 0x7415AC2: __wcsnlen_sse4_1 (strlen.S:194)
==9459==    by 0x7403458: wcsnrtombs (wcsnrtombs.c:58)
==9459==    by 0x6896E6D: std::codecvt<wchar_t, char, __mbstate_t>::do_out(__mbstate_t&, wchar_t const*, wchar_t const*, wchar_t const*&, char*, char*, char*&) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==9459==    by 0x50551B1: boost::filesystem::path_traits::convert(wchar_t const*, wchar_t const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::codecvt<wchar_t, char, __mbstate_t> const&) (in /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1)
==9459==    by 0x505563A: boost::filesystem::detail::unique_path(boost::filesystem::path const&, boost::system::error_code*) (in /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1)
==9459==    by 0x521FC5: ??? (in /usr/bin/bitcoind)
==9459==    by 0x15B683: ??? (in /usr/bin/bitcoind)
==9459==    by 0x15BA54: ??? (in /usr/bin/bitcoind)
==9459==    by 0x155C52: ??? (in /usr/bin/bitcoind)
==9459==    by 0x1451FE: ??? (in /usr/bin/bitcoind)
==9459==    by 0x7366B96: (below main) (libc-start.c:310)
==9459==  Address 0x8657de0 is 0 bytes after a block of size 80 alloc'd
==9459==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9459==    by 0x691FCAA: std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_mutate(unsigned long, unsigned long, wchar_t const*, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==9459==    by 0x6920B02: std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_replace(unsigned long, unsigned long, wchar_t const*, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==9459==    by 0x5054F11: boost::filesystem::path_traits::convert(char const*, char const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, std::codecvt<wchar_t, char, __mbstate_t> const&) (in /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1)
==9459==    by 0x50556F7: boost::filesystem::detail::unique_path(boost::filesystem::path const&, boost::system::error_code*) (in /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1)
==9459==    by 0x521FC5: ??? (in /usr/bin/bitcoind)
==9459==    by 0x15B683: ??? (in /usr/bin/bitcoind)
==9459==    by 0x15BA54: ??? (in /usr/bin/bitcoind)
==9459==    by 0x155C52: ??? (in /usr/bin/bitcoind)
==9459==    by 0x1451FE: ??? (in /usr/bin/bitcoind)
==9459==    by 0x7366B96: (below main) (libc-start.c:310)
==9459==
==9459== Invalid read of size 16
==9459==    at 0x7415AC7: __wcsnlen_sse4_1 (strlen.S:194)
==9459==    by 0x7403458: wcsnrtombs (wcsnrtombs.c:58)
==9459==    by 0x6896E6D: std::codecvt<wchar_t, char, __mbstate_t>::do_out(__mbstate_t&, wchar_t const*, wchar_t const*, wchar_t const*&, char*, char*, char*&) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==9459==    by 0x50551B1: boost::filesystem::path_traits::convert(wchar_t const*, wchar_t const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::codecvt<wchar_t, char, __mbstate_t> const&) (in /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1)
==9459==    by 0x505563A: boost::filesystem::detail::unique_path(boost::filesystem::path const&, boost::system::error_code*) (in /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1)
==9459==    by 0x521FC5: ??? (in /usr/bin/bitcoind)
==9459==    by 0x15B683: ??? (in /usr/bin/bitcoind)
==9459==    by 0x15BA54: ??? (in /usr/bin/bitcoind)
==9459==    by 0x155C52: ??? (in /usr/bin/bitcoind)
==9459==    by 0x1451FE: ??? (in /usr/bin/bitcoind)
==9459==    by 0x7366B96: (below main) (libc-start.c:310)
==9459==  Address 0x8657df0 is 16 bytes after a block of size 80 alloc'd
==9459==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9459==    by 0x691FCAA: std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_mutate(unsigned long, unsigned long, wchar_t const*, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==9459==    by 0x6920B02: std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_replace(unsigned long, unsigned long, wchar_t const*, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==9459==    by 0x5054F11: boost::filesystem::path_traits::convert(char const*, char const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, std::codecvt<wchar_t, char, __mbstate_t> const&) (in /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1)
==9459==    by 0x50556F7: boost::filesystem::detail::unique_path(boost::filesystem::path const&, boost::system::error_code*) (in /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1)
==9459==    by 0x521FC5: ??? (in /usr/bin/bitcoind)
==9459==    by 0x15B683: ??? (in /usr/bin/bitcoind)
==9459==    by 0x15BA54: ??? (in /usr/bin/bitcoind)
==9459==    by 0x155C52: ??? (in /usr/bin/bitcoind)
==9459==    by 0x1451FE: ??? (in /usr/bin/bitcoind)
==9459==    by 0x7366B96: (below main) (libc-start.c:310)
==9459==
Bitcoin server starting
==9459==
==9459== HEAP SUMMARY:
==9459==     in use at exit: 2,275,744 bytes in 2,613 blocks
==9459==   total heap usage: 3,693 allocs, 1,080 frees, 6,734,872 bytes allocated
==9459==
==9459== LEAK SUMMARY:
==9459==    definitely lost: 77 bytes in 1 blocks
==9459==    indirectly lost: 0 bytes in 0 blocks
==9459==      possibly lost: 0 bytes in 0 blocks
==9459==    still reachable: 2,275,667 bytes in 2,612 blocks
==9459==                       of which reachable via heuristic:
==9459==                         newarray           : 48 bytes in 1 blocks
==9459==         suppressed: 0 bytes in 0 blocks
==9459== Rerun with --leak-check=full to see details of leaked memory
==9459==
==9459== For counts of detected and suppressed errors, rerun with: -v
==9459== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
root@hostname:~# ==9460==
==9460== Process terminating with default action of signal 11 (SIGSEGV)
==9460==  Access not within mapped region at address 0x4079FF8
==9460==    at 0x51BC14: ??? (in /usr/bin/bitcoind)
==9460==    by 0x7388040: __run_exit_handlers (exit.c:108)
==9460==    by 0x7388139: exit (exit.c:139)
==9460==    by 0x7366B9D: (below main) (libc-start.c:344)
==9460==  If you believe this happened as a result of a stack
==9460==  overflow in your program's main thread (unlikely but
==9460==  possible), you can try to increase the size of the
==9460==  main thread stack using the --main-stacksize= flag.
==9460==  The main thread stack size used in this run was 8388608.
==9460==
==9460== HEAP SUMMARY:
==9460==     in use at exit: 17,672 bytes in 223 blocks
==9460==   total heap usage: 3,761 allocs, 3,538 frees, 6,742,965 bytes allocated
==9460==
==9460== LEAK SUMMARY:
==9460==    definitely lost: 48 bytes in 1 blocks
==9460==    indirectly lost: 0 bytes in 0 blocks
==9460==      possibly lost: 0 bytes in 0 blocks
==9460==    still reachable: 17,624 bytes in 222 blocks
==9460==         suppressed: 0 bytes in 0 blocks
==9460== Rerun with --leak-check=full to see details of leaked memory
==9460==
==9460== For counts of detected and suppressed errors, rerun with: -v
==9460== ERROR SUMMARY: 3 errors from 2 contexts (suppressed: 0 from 0)

**Comment by luke-jr** [comment]
Please try a newer version and close this if it's fixed

**Comment by freerko** [comment]
thanks, now it works!
