### ISSUE TITLE
https://coin.dance/ statistics

### ISSUE THREAD

**Issue by molnard** [bitcoinknots/bitcoin#26]
**Is your feature request related to a problem? Please describe.**

Wasabi is using Knots since [v1.1.11](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v1.1.11). Shouldn't the number of Knots nodes increased a bit, at least slightly?

According to https://coin.dance/nodes/knots there is no change since then. 

- Do you know how are they measuring their numbers?
- If coin.dance is not valid is there another site where we can get some relevant statistics?

**Comment by ghost** [comment]
> Wasabi is using Knots since v1.1.11

Is Wasabi still using Knots? @molnard 

> If coin.dance is not valid is there another site where we can get some relevant statistics?

I see 174 Bitcoin Knots nodes here: https://luke.dashjr.org/programs/bitcoin/files/charts/software.html

**Comment by molnard** [comment]
It is optional, but if the user turns on the full node feature Wasabi will use Knots that was shipped with the software itself. 

Maybe they are not counted as Knots are only running when Wasabi is running?

**Comment by ghost** [comment]
> Maybe they are not counted as Knots are only running when Wasabi is running?

Not sure

**Comment by luke-jr** [comment]
Seems like more of an issue in coin.dance than Knots?
