### ISSUE TITLE
software expired message

### ISSUE THREAD

**Issue by dillton2010** [bitcoinknots/bitcoin#29]
I haven't opened the program in a while and when I try to open it it is says "this software is expired, and my be out of consensus.You musy choose to upgrade or override this expiration." If anyone has any ideas to solve this that would be great. Thanks

**Comment by luke-jr** [comment]
Only very old (and unsupported) versions should show this message. What version are you using?

If you *really* don't want to upgrade, set `-softwareexpiry=0` to bypass it.

**Comment by MaloMax** [comment]
same here . 
![Schermata del 2024-01-06 10-00-33](https://github.com/bitcoinknots/bitcoin/assets/39829095/a6e52c44-647f-45a4-887b-fb09500b88f8)
