### ISSUE TITLE
Change "The Bitcoin Core developers" to "The Bitcoin Knots developers"

### ISSUE THREAD

**Issue by ghost** [bitcoinknots/bitcoin#35]
![image](https://user-images.githubusercontent.com/13405205/135704930-2fe8d6ec-f59c-46b9-a7ca-aff542fed154.png)

**Comment by ghost** [comment]
Cc: @luke-jr

**Comment by luke-jr** [comment]
Why?

**Comment by ghost** [comment]
Knots isn't maintained by Core developers. If the implementation, logo and everything else is different why not this?

**Comment by luke-jr** [comment]
But it *is* maintained by Core developers...
