### ISSUE TITLE
cli: make -getinfo user friendly

### ISSUE THREAD

**Issue by ghost** [bitcoinknots/bitcoin#37]
Does it make sense to add changes from https://github.com/bitcoin/bitcoin/pull/21832, 
https://github.com/bitcoin/bitcoin/pull/22547
and https://github.com/bitcoin/bitcoin/pull/22891?

`-getinfo` looks like this right now:

![image](https://user-images.githubusercontent.com/13405205/135714888-7eee3102-b164-4ac0-b8ae-bf9904ed14ed.png)

after adding changes from above 3 PRs it will look like this:

![image](https://github.com/prayank23/bitcoin/raw/gif/mempool-getinfo.gif)

**Comment by luke-jr** [comment]
Probably. Unfortunately, at least the first one simply has too many conflicts for me to handle right now. I've got the other two marked as TODO, but that to-do includes evaluating feasibility for merging.
