### ISSUE TITLE
BitcoinKnots should link to RGB libraries

### ISSUE THREAD

**Issue by bstin** [bitcoinknots/bitcoin#41]
**Is your feature request related to a problem? Please describe.**
RGB Protocol is not a token, nor a chain, nor an upgrade to Bitcoin Protocol. It simply uses existing Bitcoin / LN to enable Assets / Securities / SmartContracts / NFT's, etc

Its a set of libraries (or daemons) that can be linked at runtime to provide this "enhanced experience"

**Describe the solution you'd like**
BitcoinKnots should take the lead in integrating RGB libs into main wallet.

**Describe alternatives you've considered**
There are no other alternatives currently that fit as well with Bitcoin Core goals. This is just "Really Good Bitcoin". No needless blockchains, sidechains, mergedmining, uneeded tokens, etc. This is just a library that helps BTC leapfrog all other "uneeded tokens" (ie. ETH). 

**Additional context**

**Comment by ghost** [comment]
> BitcoinKnots should take the lead in integrating RGB libs into main wallet.

Which library?

**Comment by bstin** [comment]
I'm not a developer, but I would imagine its RGB-Node. 

https://github.com/rgb-org/rgb-node
