### ISSUE TITLE
Add Bitcoin Knots in winget-pkgs

### ISSUE THREAD

**Issue by ghost** [bitcoinknots/bitcoin#45]
@luke-jr Bitcoin Core is added in the below link, should we submit a pull request to add Knots?

https://github.com/microsoft/winget-pkgs/tree/master/manifests/b/BitcoinCoreProject

**Comment by luke-jr** [comment]
I don't see any reason not to

**Comment by ghost** [comment]
We will need a page with privacy policy to add Knots in winget-pkgs. 

https://github.com/bitcoinknots/knots-www/pull/5

**Comment by luke-jr** [comment]
It's optional: https://github.com/microsoft/winget-pkgs/issues/330#issuecomment-772901285

I don't know why packaging the program would care about a privacy policy for the webpage...?

**Comment by ghost** [comment]
Thanks I was not aware its optional. Will remove that and try to add knots again.
