### ISSUE TITLE
[p2p] Unsupported format of addrman database

### ISSUE THREAD

**Issue by ghost** [bitcoinknots/bitcoin#46]
I got this error today while running Knots:

```
2022-02-02T14:04:51Z ERROR: DeserializeDB: Deserialize or I/O error - Unsupported format of addrman database: 4. It is compatible with formats >=4, but the maximum supported by this version of Bitcoin Knots is 3.: iostream error
```

**Comment by luke-jr** [comment]
Probably you ran Core master at some point? 22.x only supports addrman v3.

Is this a warning or an error preventing Knots from starting? Does Core behave the same way?

**Comment by luke-jr** [comment]
Ref https://github.com/bitcoin/bitcoin/issues/24188

**Comment by ghost** [comment]
> Probably you ran Core master at some point?

Yes

> Is this a warning or an error preventing Knots from starting? 

Warning because `bitcoind` was still running

> Does Core behave the same way?

Will try today
