### ISSUE TITLE
bitcoin-qt Warning: Unrecognised block version being mined! - unable to remove warning

### ISSUE THREAD

**Issue by Tracachang** [bitcoinknots/bitcoin#49]
When an unrecognised block version is being mined there is a warning in bitcoinknots-qt but there is no way to close or remove the warning.
<img src="https://i.ibb.co/bgWL0PD/knots.png">

**Expected behavior**

After acknowledge the warning there should a way to close/remove this warning since it may be old, the only way to "remove" it is restarting the client.

**System information**

bitcoin-22.0.knots20211108

Manjaro

**Comment by luke-jr** [comment]
This should be resolved now, can you confirm?

**Comment by Tracachang** [comment]
Yes I do confirm, resolved.
