### ISSUE TITLE
locked bitcoin

### ISSUE THREAD

**Issue by wmacevoy** [bitcoinknots/bitcoin#5]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue

On attempting to install bitcoin knots, the update locks after 168472 blocks.  The installation is as follows:

1. Bitcoin Knots version v0.14.0.0-46952c8-dirty (64-bit)
2. Launch and close.
3. Copy old wallet.dat to ~/Library/Application Support/Bitcoin
4. Erase blocks.
5. Relaunch

Currently locked with:

version: v0.14.0.0-46952c8-dirty
user agent: /Satoshi:0.14.0/Knots:20170307/
Berkeley db version: Berkeley DB 4.8.30: (April  9, 2010)
Startup time: Sun Apr 16 22:38:09 2017
Name: main
connections: 5 (in: 0/out: 5)
current number of blocks: 293774
last block time: Wed Apr 2 09:20:19 2014

network traffic: rx: 16gb, tx 17mb

peers: 3572 / 40.30.151.56:8333 (changing)...

#### If so, please list the steps to reproduce below:

Can't say reliably.  Bitcoin wallet consistently locks up somewhere while trying to synchronize.  My looking at the debug window apparently did something; it is now updating blocks again (2 years and 37 weeks left until synced).  Once the computer shuts down the screen (I have hibernate never) something changes which stops the chain update and does not want to start again.

### Expected behaviour
The block chain should be updated, even if it is long enough (expected time originally was 8 hours) so have the system go into standby and back.

### Actual behaviour
The block chain locks up, with no updates and no restart even when viewing the application.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

version: v0.14.0.0-46952c8-dirty
user agent: /Satoshi:0.14.0/Knots:20170307/
Berkeley db version: Berkeley DB 4.8.30: (April  9, 2010)

### Machine specs:
- OS: macOS Sierra 10.12.4
- CPU: 2.5 GHz Intel Core i5
- RAM: 16GB
- Disk size: 2TB
- Disk Type (HD/SDD): Fusion Drive (SSD/HDD combo)

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

The contents of debug.log is 7GB --- I can add parts if suggested.

**Comment by luke-jr** [comment]
How about everything after the last `UpdateTip` line of debug.log?

**Comment by wmacevoy** [comment]
sooo many  update tips.  It stopped again (this time I have never sleep never turn off display).  After poking at the UI (Debug window I think brings it back to life, perhaps after looking at the peers section of the debug), it started ticking through blocks again.

**Comment by wmacevoy** [comment]
Found a  break in the log: 

> connect() to [2a01:9e40::1:225:90ff:feac:8ffe]:8333 failed: No route to host (65)

Here is the context, the error happens right after the 2017-04-18 23:08:40 log entry.  It looks like it locks up (hours) before this.  The previous log entry is hours old.

> 2017-04-17 06:19:52 UpdateTip: new best=0000000000000000c246566443b05eda0f78d8fee3f81be923739ea36911d621 height=293774 version=0x00000002 log2_work=77.701174 tx=36085339 date='2014-04-02 15:20:19' progress=0.169339 cache=341.6MiB(416656tx)
> 2017-04-17 06:19:52 UpdateTip: new best=00000000000000001b006580230f8adc0ffbc3fc0f74c6a1f7ca255e2ff947df height=293775 version=0x00000002 log2_work=77.7013 tx=36085467 date='2014-04-02 15:22:24' progress=0.169339 cache=341.6MiB(416797tx)
> 2017-04-17 06:19:52 UpdateTip: new best=00000000000000008d09637d44302bf56a023bb8f7cc4e9975bd90fbc0d98146 height=293776 version=0x00000002 log2_work=77.701426 tx=36085563 date='2014-04-02 15:23:18' progress=0.169340 cache=341.6MiB(416845tx)
> 2017-04-18 23:08:40 UpdateTip: new best=0000000000000000bf3463576d69c64d951c0f52790a263978e7469345be8f35 height=293777 version=0x00000002 log2_work=77.701553 tx=36085802 date='2014-04-02 15:28:22' progress=0.168968 cache=341.7MiB(416936tx)connect() to [2a01:9e40::1:225:90ff:feac:8ffe]:8333 failed: No route to host (65)
> 2017-04-18 23:08:42 UpdateTip: new best=00000000000000007082074b212519ac27a2273f6d3059f4ae06b0a5e51e9dd3 height=293778 version=0x00000002 log2_work=77.701679 tx=36085963 date='2014-04-02 15:29:56' progress=0.168969 cache=341.7MiB(417027tx)
> 2017-04-18 23:08:42 UpdateTip: new best=00000000000000007cc61718df8d87ac4d7929daa3ec0d491ee9126973c9c9f8 height=293779 version=0x00000002 log2_work=77.701805 tx=36086676 date='2014-04-02 15:42:03' progress=0.168972 cache=341.8MiB(417482tx)
> 2017-04-18 23:09:00 UpdateTip: new best=00000000000000005215e4d087e7a35df94c87b9283d493449d7969a4202bef6 height=293780 version=0x00000002 log2_work=77.701931 tx=36087771 date='2014-04-02 16:15:42' progress=0.168977 cache=21.3MiB(2322tx)
> 2017-04-18 23:09:04 UpdateTip: new best=0000000000000000aade4f3d1e87b238dc82a2639afd276a7a8f338e725f242f height=293781 version=0x00000002 log2_work=77.702058 tx=36088283 date='2014-04-02 16:19:35' progress=0.168980 cache=23.0MiB(3439tx)
>

**Comment by luke-jr** [comment]
Looks unrelated.

**Comment by wmacevoy** [comment]
Ok - there are many similar connect() errors, but this is the only one that does not have it's own log entry.  Others are like:

> 2017-04-17 07:32:55 connect() to [2001::9d38:6abd:4f6:1ff0:a5b0:e210]:8333 failed: No route to host (65)
> 2017-04-17 07:33:16 connect() to 91.96.18.127:8333 failed after select(): Connection refused (61)
> 2017-04-17 07:38:09 connect() to [2001::5ef5:79fb:1c80:1ed9:2b8f:68b5]:8333 failed: No route to host (65)
> 2017-04-17 07:39:36 connect() to [2001::9d38:78cf:180d:10c1:2616:d15a]:8333 failed: No route to host (65)
> 2017-04-17 07:41:44 connect() to [2001::9d38:953c:1057:3462:51b1:7a10]:8333 failed: No route to host (65)

... and at least surprisingly close to the long gap in progress.

**Comment by luke-jr** [comment]
It's unlikely any of these are related... Instead of trying to pick out relevant bits, just pastebin everything from the last UpdateTip onward...

**Comment by wmacevoy** [comment]
Sorry didn't realize I had grepped out messages.  Here is a section from a little before the last update to after updates started to happen again:

https://drive.google.com/open?id=0ByBPjWWp3nRqTHd2T2JqeVlGLUk

**Comment by wmacevoy** [comment]
And ... now that it was updating again .. (!) ... I get a db error, followed by a restart, followed by a fatal internal error, followed by rewinding blocks....

https://drive.google.com/open?id=0ByBPjWWp3nRqV3d5ZmJWLTFPVTQ

:o(


Between this I stoped the client (which exited correctly) then copied out the logs to start from a clean point, erased them, then restarted the client.

**Comment by luke-jr** [comment]
Is it possible you have failing/defective hardware? Have you tried any other full node software on this system?

**Comment by wmacevoy** [comment]
Just put a new drive in (a failed drive is why I'm restoring the system).   I tried Bitcoin Core with similar results.  I'll try a memory test ....  although BitCoin core seems to be locked up on the "rewinding blocks" now.  I'll just kill it and (sigh) start again.

**Comment by luke-jr** [comment]
Given the errors you were seeing, I'd suspect either bad RAM or bad CPU before bad storage. :(

You're not overclocking, right?

**Comment by wmacevoy** [comment]
.... just did a memory test and it failed.  Ordered new ram.  I'll post to this in about two weeks after installing and trying again.  Thanks for following through this and I hope I'm back soon with good news.

**Comment by wmacevoy** [comment]
Thank you!  Yes the same system with new ram performed without misbehaving; I just caught up on the blockchain last night.

**Comment by luke-jr** [comment]
Phew, good to hear :)
