### ISSUE TITLE
Add a max buffer mem params ?

### ISSUE THREAD

**Issue by Jorropo** [bitcoinknots/bitcoin#9]
### Describe the issue
I have only 1 Gb of ram (rpi3), and bitcoin knots is the unique program running on (except sshd or sys).
And the buffer is growing and growing and after 6H I running out of memory.
A lot of person will say : "use a swap". But I can't, performance will be to low.

#### If so, please list the steps to reproduce below:
1. Use all ram of the system.

### Expected behaviour
Add a params for set max buffer at N Mb.

### Actual behaviour
Use more and more ram and reach the crash.

### What version of Bitcoin Knots are you using?
Official binary, v0.14.2.knots20170618 aarch64

### Machine specs:
- OS:raspbian
- CPU:1.2GHz 4core
- RAM: 1Gb (1024 Kb)
- Disk size: 16 Gb (card for os), 320 GB HDD (symbolique linked for blockchain ("/home/$USER/.bitcoin/" to /media/$USER/[HHD partition]/bitcoin/))

thx to read it :)

**Comment by luke-jr** [comment]
See "Keep the transaction memory pool below _______ MB" in Mempool options or "Size of database cache" in Main options

**Comment by Jorropo** [comment]
thx sorry, i didn't see it.
